-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_DUE_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_DELETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_ADDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_REMOVED';
