export const SEED_PASSWORD = "TeamUp2026!";

export const GAZA_UNIVERSITIES = [
  { name: "Islamic University of Gaza", code: "IUG", country: "Palestine" },
  { name: "Al-Azhar University - Gaza", code: "AUG", country: "Palestine" },
  { name: "Al-Aqsa University", code: "AAQ", country: "Palestine" },
  { name: "University College of Applied Sciences (UCAS)", code: "UCAS", country: "Palestine" },
  { name: "Gaza University", code: "GU", country: "Palestine" },
  { name: "Palestine Technical College - Deir al-Balah", code: "PTC", country: "Palestine" },
  { name: "Al-Quds Open University - Gaza Branch", code: "QOU", country: "Palestine" },
  { name: "Palestine University - Gaza", code: "PUG", country: "Palestine" },
  { name: "Israa University", code: "ISRA", country: "Palestine" },
  { name: "University of Palestine", code: "UOP", country: "Palestine" },
  { name: "American University of Gaza", code: "AUGZ", country: "Palestine" },
  { name: "University of Science and Technology - Gaza", code: "UST", country: "Palestine" },
] as const;

export type SeedUserSpec = {
  key: string;
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  role: "SYSTEM_ADMIN" | "MENTOR" | "STUDENT" | "GRADUATE";
  major: string;
  skills: string[];
  bio: string;
};

export const SEED_USERS: SeedUserSpec[] = [
  {
    key: "admin",
    email: "admin@teamup.test",
    username: "teamup_admin",
    firstName: "System",
    lastName: "Admin",
    role: "SYSTEM_ADMIN",
    major: "Platform Administration",
    skills: ["Operations", "Moderation", "Analytics"],
    bio: "TeamUp platform administrator.",
  },
  {
    key: "mentor_sara",
    email: "mentor.sara@teamup.test",
    username: "sara_hassan",
    firstName: "Sara",
    lastName: "Hassan",
    role: "MENTOR",
    major: "Software Engineering",
    skills: ["React", "Node.js", "Mentoring", "System Design"],
    bio: "Senior software engineer mentoring graduation teams in Gaza.",
  },
  {
    key: "mentor_omar",
    email: "mentor.omar@teamup.test",
    username: "omar_khaled",
    firstName: "Omar",
    lastName: "Khaled",
    role: "MENTOR",
    major: "Computer Science",
    skills: ["Python", "Machine Learning", "Healthcare Tech"],
    bio: "Mentor focused on health-tech and AI graduation projects.",
  },
  {
    key: "mentor_lina",
    email: "mentor.lina@teamup.test",
    username: "lina_awad",
    firstName: "Lina",
    lastName: "Awad",
    role: "MENTOR",
    major: "Information Systems",
    skills: ["Product Management", "UX", "Agile"],
    bio: "Helps student teams ship usable products on time.",
  },
  {
    key: "student_ahmad",
    email: "student.ahmad@teamup.test",
    username: "ahmad_nasser",
    firstName: "Ahmad",
    lastName: "Nasser",
    role: "STUDENT",
    major: "Computer Engineering",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL"],
    bio: "Final-year student building a smart campus platform.",
  },
  {
    key: "student_maya",
    email: "student.maya@teamup.test",
    username: "maya_faris",
    firstName: "Maya",
    lastName: "Faris",
    role: "STUDENT",
    major: "Computer Science",
    skills: ["UI Design", "Figma", "React"],
    bio: "Frontend developer and UX enthusiast.",
  },
  {
    key: "student_karim",
    email: "student.karim@teamup.test",
    username: "karim_saleh",
    firstName: "Karim",
    lastName: "Saleh",
    role: "STUDENT",
    major: "Computer Science",
    skills: ["Express", "Prisma", "Docker"],
    bio: "Backend-focused student developer.",
  },
  {
    key: "student_nour",
    email: "student.nour@teamup.test",
    username: "nour_hamed",
    firstName: "Nour",
    lastName: "Hamed",
    role: "STUDENT",
    major: "Information Technology",
    skills: ["Testing", "QA", "Documentation"],
    bio: "Quality assurance lead on team projects.",
  },
  {
    key: "student_yousef",
    email: "student.yousef@teamup.test",
    username: "yousef_ali",
    firstName: "Yousef",
    lastName: "Ali",
    role: "STUDENT",
    major: "Software Engineering",
    skills: ["JavaScript", "Mobile", "Firebase"],
    bio: "Looking for a team to join — no active workspace.",
  },
  {
    key: "student_dina",
    email: "student.dina@teamup.test",
    username: "dina_mahmoud",
    firstName: "Dina",
    lastName: "Mahmoud",
    role: "STUDENT",
    major: "Data Science",
    skills: ["Python", "Pandas", "Data Visualization"],
    bio: "Interested in AI and civic-tech projects.",
  },
  {
    key: "student_tarek",
    email: "student.tarek@teamup.test",
    username: "tarek_ibrahim",
    firstName: "Tarek",
    lastName: "Ibrahim",
    role: "STUDENT",
    major: "Biomedical Engineering",
    skills: ["Healthcare", "React Native", "APIs"],
    bio: "Leading a telemedicine graduation project.",
  },
  {
    key: "student_hana",
    email: "student.hana@teamup.test",
    username: "hana_qasem",
    firstName: "Hana",
    lastName: "Qasem",
    role: "STUDENT",
    major: "Computer Science",
    skills: ["React", "Tailwind", "REST APIs"],
    bio: "Full-stack student developer.",
  },
  {
    key: "student_sami",
    email: "student.sami@teamup.test",
    username: "sami_jawad",
    firstName: "Sami",
    lastName: "Jawad",
    role: "STUDENT",
    major: "Information Systems",
    skills: ["Networking", "Security", "Linux"],
    bio: "Sent a pending join request to the telemedicine team.",
  },
  {
    key: "student_laila",
    email: "student.laila@teamup.test",
    username: "laila_omar",
    firstName: "Laila",
    lastName: "Omar",
    role: "STUDENT",
    major: "Artificial Intelligence",
    skills: ["Python", "TensorFlow", "NLP"],
    bio: "Submitted an AI tutoring project for mentor review.",
  },
  {
    key: "student_fadi",
    email: "student.fadi@teamup.test",
    username: "fadi_mansour",
    firstName: "Fadi",
    lastName: "Mansour",
    role: "STUDENT",
    major: "Computer Science",
    skills: ["Django", "PostgreSQL", "DevOps"],
    bio: "Member of a submitted graduation project team.",
  },
  {
    key: "graduate_rana",
    email: "graduate.rana@teamup.test",
    username: "rana_sbeih",
    firstName: "Rana",
    lastName: "Sbeih",
    role: "GRADUATE",
    major: "Business Informatics",
    skills: ["Product", "Marketing", "No-code"],
    bio: "Graduate publishing project ideas on the marketplace.",
  },
  {
    key: "graduate_haitham",
    email: "graduate.haitham@teamup.test",
    username: "haitham_zu",
    firstName: "Haitham",
    lastName: "Zu",
    role: "GRADUATE",
    major: "Computer Engineering",
    skills: ["IoT", "Embedded Systems", "C++"],
    bio: "Graduate student exploring new team opportunities.",
  },
  {
    key: "graduate_monira",
    email: "graduate.monira@teamup.test",
    username: "monira_deeb",
    firstName: "Monira",
    lastName: "Deeb",
    role: "GRADUATE",
    major: "Software Engineering",
    skills: ["Java", "Spring", "Cloud"],
    bio: "Posts paid and free project ideas for students.",
  },
  {
    key: "graduate_ziad",
    email: "graduate.ziad@teamup.test",
    username: "ziad_barakat",
    firstName: "Ziad",
    lastName: "Barakat",
    role: "GRADUATE",
    major: "Cybersecurity",
    skills: ["Security", "Pen-testing", "Linux"],
    bio: "Graduate available to join a new team.",
  },
  {
    key: "student_reem",
    email: "student.reem@teamup.test",
    username: "reem_adel",
    firstName: "Reem",
    lastName: "Adel",
    role: "STUDENT",
    major: "Graphic Design",
    skills: ["Branding", "Illustration", "UI"],
    bio: "Designer who deleted a previous project and can join again.",
  },
];
